name: Kafka Architecture Analysis

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install networkx pydot matplotlib

    - name: Debug Environment
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents before analysis:"
        ls -la
        
    - name: Analyze Architecture
      run: |
        echo "Running analysis..."
        python .github/scripts/analyze_architecture.py
        echo "Analysis complete. Directory contents after analysis:"
        ls -la
        
    - name: Upload Analysis Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: architecture-analysis
        path: |
          architecture_report.txt
          dependency_graph.png